src/objects/Territory__c.object
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TerrUser__c.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>TerrUsers</relationshipLabel>
        <relationshipName>TerritoryTerrUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTerrUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TerrUser</label>
    <nameField>
        <displayFormat>TU-{0000}</displayFormat>
        <label>Terr Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerrUsers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RecalculateSharingsChain.cls
/**
 * Created by Макс on 01.10.2019.
 */

public with sharing class RecalculateSharingsChain {

    public static void recalculateWholeChain(Set<Id> users){
        system.debug('recalculateSharingChain');

        List<Territory__Share> terrShares = recalculateTerritories(users);
        List<AccountShare> accountShares = recalculateAccounts(terrShares);
        recalculateContacts(accountShares);
    }

    public static List<Territory__Share> recalculateTerritories(Set<Id> users){
        system.debug('recalculateTerritories');

        List<TerrUser__c> terrToUser = new List<TerrUser__c>([
                SELECT Id, Territory__c, User__c
                FROM TerrUser__c
                WHERE User__c IN :users
        ]);

        List<Territory__Share> terrShares = PerformTerritorySharingsDML.insertTerritoryShares(terrToUser);

        return terrShares;
    }

    public static List<AccountShare> recalculateAccounts(List<Territory__Share> territorySharings){
        system.debug('recalculateAccounts');

        List<AccountShare> accountShares = PerformAccountSharingsDML.insertAccountShares(territorySharings);

        return accountShares;
    }

    public static void recalculateContacts(List<AccountShare> accountSharings){
        system.debug('recalculateContacts');

        PerformContactSharesDML.insertContactShares(accountSharings);
    }

}